# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kalkulator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(214, 358)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dobZeroButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("00"))
        self.dobZeroButton.setGeometry(QtCore.QRect(10, 280, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dobZeroButton.setFont(font)
        self.dobZeroButton.setObjectName("dobZeroButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("0"))
        self.zeroButton.setGeometry(QtCore.QRect(60, 280, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.zeroButton.setFont(font)
        self.zeroButton.setObjectName("zeroButton")
        self.dotButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.dot_it())
        self.dotButton.setGeometry(QtCore.QRect(110, 280, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dotButton.setFont(font)
        self.dotButton.setObjectName("dotButton")
        self.eqButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.math_it())
        self.eqButton.setGeometry(QtCore.QRect(160, 280, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.eqButton.setFont(font)
        self.eqButton.setObjectName("eqButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("1"))
        self.oneButton.setGeometry(QtCore.QRect(10, 230, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("2"))
        self.twoButton.setGeometry(QtCore.QRect(60, 230, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.twoButton.setFont(font)
        self.twoButton.setObjectName("twoButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("3"))
        self.threeButton.setGeometry(QtCore.QRect(110, 230, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.threeButton.setFont(font)
        self.threeButton.setObjectName("threeButton")
        self.addButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("+"))
        self.addButton.setGeometry(QtCore.QRect(160, 230, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("4"))
        self.fourButton.setGeometry(QtCore.QRect(10, 180, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("5"))
        self.fiveButton.setGeometry(QtCore.QRect(60, 180, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("6"))
        self.sixButton.setGeometry(QtCore.QRect(110, 180, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("-"))
        self.minusButton.setGeometry(QtCore.QRect(160, 180, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("7"))
        self.sevenButton.setGeometry(QtCore.QRect(10, 130, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sevenButton.setFont(font)
        self.sevenButton.setObjectName("sevenButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("8"))
        self.eightButton.setGeometry(QtCore.QRect(60, 130, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.eightButton.setFont(font)
        self.eightButton.setObjectName("eightButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("9"))
        self.nineButton.setGeometry(QtCore.QRect(110, 130, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        self.timesButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("*"))
        self.timesButton.setGeometry(QtCore.QRect(160, 130, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.timesButton.setFont(font)
        self.timesButton.setObjectName("timesButton")
        self.acButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("AC"))
        self.acButton.setGeometry(QtCore.QRect(10, 80, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.acButton.setFont(font)
        self.acButton.setObjectName("acButton")
        self.delButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.del_it())
        self.delButton.setGeometry(QtCore.QRect(60, 80, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.delButton.setFont(font)
        self.delButton.setObjectName("delButton")
        self.percentButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("%"))
        self.percentButton.setGeometry(QtCore.QRect(110, 80, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.percentButton.setFont(font)
        self.percentButton.setObjectName("percentButton")
        self.divButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.click("/"))
        self.divButton.setGeometry(QtCore.QRect(160, 80, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.divButton.setFont(font)
        self.divButton.setObjectName("divButton")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 10, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.outputLabel.setFont(font)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 60, 201, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 214, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    #mathematic functionality
    def math_it(self):
        screen = self.outputLabel.text()
        try:
            # Do the math
            answer = eval(screen)
            # Output the answer
            self.outputLabel.setText(str(answer))
        except:
            #Output error to the screen
            self.outputLabel.setText("ERROR")


    def del_it(self):
        screen = self.outputLabel.text()
        screen = screen[:-1]

        if(len(screen) == 0):
            self.outputLabel.setText("0")
        else:
            self.outputLabel.setText(screen)


    def dot_it(self):
        screen = self.outputLabel.text()
        chars = ["+", "-", "*", "/"]
        rescreen = screen[::-1]
  
        if "." not in screen:
            self.outputLabel.setText(f'{screen}.')
        for char in chars:
            if char in rescreen and "." not in rescreen[:rescreen.index(char)]:
                self.outputLabel.setText(f'{screen}.')
                
                

    def click(self, clicked):
        if clicked == "AC":
            self.outputLabel.setText("0")   
        else: 
            # untuk mengecek apakah label diawali angka 0 atau tidak
            if self.outputLabel.text() == "0":
                self.outputLabel.setText("")
            # concatinate label
            self.outputLabel.setText(f'{self.outputLabel.text()}{clicked}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.dobZeroButton.setText(_translate("MainWindow", "00"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.dotButton.setText(_translate("MainWindow", "."))
        self.eqButton.setText(_translate("MainWindow", "="))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.addButton.setText(_translate("MainWindow", "+"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.timesButton.setText(_translate("MainWindow", "x"))
        self.acButton.setText(_translate("MainWindow", "AC"))
        self.delButton.setText(_translate("MainWindow", "DEL"))
        self.percentButton.setText(_translate("MainWindow", "%"))
        self.divButton.setText(_translate("MainWindow", "/"))
        self.outputLabel.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
